### dodaj event
POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "abc",
  "date": "2026-04-16",
  "city": "Poznań",
  "distance": 21.098
}

### wyswietl dostepne eventy
GET http://localhost:8080/events

### event po id
GET http://localhost:8080/events/6

### usun event o id
DELETE http://localhost:8080/events/9

### zapisz sie na event (eventid, runnerid)
POST http://localhost:8080/events/5/register/20

### wszystkie eventy runnera
GET http://localhost:8080/runners/1/events

### wszyscy zapisani biegacze na event
GET http://localhost:8080/events/6/runners

### usun biegacza z eventu
DELETE http://localhost:8080/events/1/register/1

