###
POST http://localhost:8080/runners/7/follow/6

###
DELETE http://localhost:8080/runners/7/follow/1

###
GET http://localhost:8080/runners/1/followers

###
GET http://localhost:8080/runners/6/following

###
GET http://localhost:8080/runners/6/feed-trainings

###
GET http://localhost:8080/runners/1/feed-all-activity