### dodanie lokalizacji do biegacza
POST http://localhost:8080/runners/12/locations
Content-Type: application/json


{
  "placeName": "Żoliborz",
  "latitude": 52.2690,
  "longitude": 20.9780
}



###
GET http://localhost:8080/locations/20

### wszystkie lokacje danego biegacza
GET http://localhost:8080/runners/11/locations

###
DELETE http://localhost:8080/locations/21