### dodanie lokalizacji do biegacza
POST http://localhost:8080/runners/4/locations
Content-Type: application/json

{
  "placeName": "Legionowo",
  "latitude": 52.4015,
  "longitude": 20.9266
}



###
GET http://localhost:8080/locations/20

### wszystkie lokacje danego biegacza
GET http://localhost:8080/runners/6/locations

###
DELETE http://localhost:8080/locations/21