###

POST http://localhost:8080/routes/generate
Content-Type: application/json

{
  "runnerId": 4,
  "startLocationId": 28,
  "endLocationId": 27,
  "plannedDistance": 4000
}


###

POST http://localhost:8080/routes/loop
Content-Type: application/json

{
  "runnerId": 1,
  "startLocationId": 9,
  "targetDistance": 15000
}

###
GET http://localhost:8080/routes/50

###
GET http://localhost:8080/routes/runners/6/routes

