###

POST http://localhost:8080/routes/generate
Content-Type: application/json

{
  "runnerId": 4,
  "startLocationId": 28,
  "endLocationId": 27,
  "plannedDistance": 6000
}


###

POST http://localhost:8080/routes/loop
Content-Type: application/json

{
  "runnerId": 4,
  "startLocationId": 27,
  "targetDistance": 10000
}

###
GET http://localhost:8080/routes/15

