###

POST http://localhost:8080/routes/generate
Content-Type: application/json

{
  "runnerId": 1,
  "startLocationId": 2,
  "endLocationId": 1,
  "plannedDistance": 6000
}


###

POST http://localhost:8080/routes/loop
Content-Type: application/json

{
  "runnerId": 1,
  "startLocationId": 1,
  "targetDistance": 5000
}