###
POST http://localhost:8080/runners
Content-Type: application/json

{
  "name": "Karolina",
  "email": "Karola97@gmail.com"
}
###

GET http://localhost:8080/runners

###

GET http://localhost:8080/runners/2

###

PUT http://localhost:8080/runners/7
Content-Type: application/json

{
  "name": "Piotrek",
  "email": "piter.pan@wp.pl"
}

###
DELETE http://localhost:8080/runners/8
