### dodanie treningu do biegacza
POST http://localhost:8080/runners/7/trainings
Content-Type: application/json

{
  "date": "2026-03-28",
  "distance": 10000,
  "time": 4996,
  "runRouteId": 70
}

### pobierz treningi dla biegacza o Id
GET http://localhost:8080/runners/1/trainings

### pobierz trening po id
GET  http://localhost:8080/trainings/12

###
DELETE http://localhost:8080/trainings/3