### dodanie treningu do biegacza
POST http://localhost:8080/runners/70/trainings
Content-Type: application/json

{
  "date": "2026-03-28",
  "distance": 8000,
  "time": 4996,
  "runRouteId": 68
}

### pobierz treningi dla biegacza o Id
GET http://localhost:8080/runners/11/trainings

### pobierz trening po id
GET  http://localhost:8080/trainings/12

###
DELETE http://localhost:8080/trainings/3